import { INewMessageState } from './types';

export const initialState: INewMessageState = {
    channels: [
        {
            channelType: 'all',
            text: '',
            buttons: [],
            buttons_inline: [],
            restrictions: {
                maxTextLength: Infinity,
                isButtonAvailable: true,
                maxButtonsCount: Infinity,
                isButtonLinkAvailable: true,
                maxButtonTextLength: Infinity,
                isButtonInlineAvailable: true,
                maxButtonsInlineCount: Infinity,
                isButtonInlineLinkAvailable: true,
                maxButtonInlineTextLength: Infinity,
            },
        },
        {
            channelType: 'vk',
            text: '',
            buttons: [],
            buttons_inline: [],
            restrictions: {
                maxTextLength: 4096,
                isButtonAvailable: true,
                maxButtonsCount: 40,
                isButtonLinkAvailable: true,
                maxButtonTextLength: Infinity,
                isButtonInlineAvailable: true,
                maxButtonsInlineCount: 10,
                isButtonInlineLinkAvailable: true,
                maxButtonInlineTextLength: Infinity,
            },
        },
        {
            channelType: 'wa',
            text: '',
            buttons: [],
            buttons_inline: [],
            restrictions: {
                maxTextLength: 1000,
                isButtonAvailable: true,
                maxButtonsCount: 10,
                isButtonLinkAvailable: false,
                maxButtonTextLength: 20,
                isButtonInlineAvailable: true,
                maxButtonsInlineCount: 3,
                isButtonInlineLinkAvailable: true,
                maxButtonInlineTextLength: 20,
            },
        },
        {
            channelType: 'tg',
            text: '',
            buttons: [],
            buttons_inline: [],
            restrictions: {
                maxTextLength: 4096,
                isButtonAvailable: true,
                maxButtonsCount: Infinity,
                isButtonLinkAvailable: false,
                maxButtonTextLength: Infinity,
                isButtonInlineAvailable: true,
                maxButtonsInlineCount: Infinity,
                isButtonInlineLinkAvailable: true,
                maxButtonInlineTextLength: 64,
            },
        },
        {
            channelType: 'sms',
            text: '',
            buttons: [],
            buttons_inline: [],
            restrictions: {
                maxTextLength: Infinity,
                isButtonAvailable: false,
                maxButtonsCount: 40,
                isButtonLinkAvailable: true,
                maxButtonTextLength: Infinity,
                isButtonInlineAvailable: false,
                maxButtonsInlineCount: 10,
                isButtonInlineLinkAvailable: true,
                maxButtonInlineTextLength: Infinity,
            },
        },
    ],
};
